import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "app/components/header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header />
      <body className={inter.className}>
    
        {children}</body>
    </html>
  );
}
